### ISSUE TITLE
How to run masakari?

### ISSUE THREAD

**Issue by ivargr** [sierraplatinum/masakari#1]
Do you have a Readme or guide on how to run this tool?

I tried to run start_server.sh and start_client.sh after cloning the repository, but that does not work.

**Comment by sierraplatinum** [comment]
Hi ivargr,
thank you for your interest in using Masakari.
The repo contains only the source files of Masakari. To use it, you have to compile it first. 
To make things easier for you, I have created a new release that includes the binaries precompiled.
You find it here: 
https://github.com/sierraplatinum/masakari/releases/tag/v1.0a

**Comment by ivargr** [comment]
Thanks!

When downloading this release and running `./start_server.sh` followed by `./start_client.sh`, I'm getting the following errors:

    Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
    Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by sierraplatinum** [comment]
Hi ivargr,
you need to install up to date Java 8 from OpenJDK or Oracle to use the latest GUI library, which is included in Java 8.
For more information, see here:
https://en.wikipedia.org/wiki/JavaFX

**Comment by ivargr** [comment]
Which minimum version of Java is required? I believe I have Java 8. `java -version` on my platform gives: `OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)`.

**Comment by sierraplatinum** [comment]
Hi ivargr,
you use an older OpenJDK version that does not provide the JavaFX stack. The easiest option to install a suitable Java version is to install the Oracle Java on your computer.
See here for a good manual to install Oracle JDK 8 on ubuntu 16.04:
https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04

I hope this will help!

**Comment by ivargr** [comment]
Thanks! That worked.
